AnketProjesi/Controllers/ChartsController.cs
using AnketProjesi.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AnketProjesi.Controllers
{
    public class ChartsController : Controller
    {
        private readonly anket3DbContext _context;

        public ChartsController(anket3DbContext context)
        {
            this._context = context;
        }

        public async Task<IActionResult> ChartsMain()
        {
            return View();
        }

        public async Task<IActionResult> MesleklerCharts()
        {
            // Mühendislerin verileri
            var anketIDsMuhendis = await _context.Ankets
                .Where(a => a.TurId == 1)
                .Select(a => a.AnketId)
            .ToListAsync();

            var aCountMuhendis = await _context.Cevaplars
                .Where(c => anketIDsMuhendis.Contains((int)c.AnketId) && c.Cevap == "a")
            .CountAsync();

            var bCountMuhendis = await _context.Cevaplars
                .Where(c => anketIDsMuhendis.Contains((int)c.AnketId) && c.Cevap == "b")
            .CountAsync();

            var cCountMuhendis = await _context.Cevaplars
                .Where(c => anketIDsMuhendis.Contains((int)c.AnketId) && c.Cevap == "c")
                .CountAsync();

            var totalMuhendis = aCountMuhendis + bCountMuhendis + cCountMuhendis;
            if (totalMuhendis == 0)
                totalMuhendis = 1;

            var percentAMuhendis = ((double)aCountMuhendis / totalMuhendis) * 100;
            var percentBMuhendis = ((double)bCountMuhendis / totalMuhendis) * 100;
            var percentCMuhendis = ((double)cCountMuhendis / totalMuhendis) * 100;

            ViewData["percentAMuhendis"] = percentAMuhendis;
            ViewData["percentBMuhendis"] = percentBMuhendis;
            ViewData["percentCMuhendis"] = percentCMuhendis;

            // Doktor verileri
            var anketIDsDoktor = await _context.Ankets
                .Where(a => a.TurId == 2)
                .Select(a => a.AnketId)
            .ToListAsync();

            var aCountDoktor = await _context.Cevaplars
                .Where(c => anketIDsDoktor.Contains((int)c.AnketId) && c.Cevap == "a")
            .CountAsync();

            var bCountDoktor = await _context.Cevaplars
                .Where(c => anketIDsDoktor.Contains((int)c.AnketId) && c.Cevap == "b")
                .CountAsync();

            var cCountDoktor = await _context.Cevaplars
                .Where(c => anketIDsDoktor.Contains((int)c.AnketId) && c.Cevap == "c")
                .CountAsync();

            var totalDoktor = aCountDoktor + bCountDoktor + cCountDoktor;
            if (totalDoktor == 0)
                totalDoktor = 1;

            var percentADoktor = ((double)aCountDoktor / totalDoktor) * 100;
            var percentBDoktor = ((double)bCountDoktor / totalDoktor) * 100;
            var percentCDoktor = ((double)cCountDoktor / totalDoktor) * 100;

            ViewData["percentADoktor"] = percentADoktor;
            ViewData["percentBDoktor"] = percentBDoktor;
            ViewData["percentCDoktor"] = percentCDoktor;

            // Memur verileri
            var anketIDsMemur = await _context.Ankets
                .Where(a => a.TurId == 3)
                .Select(a => a.AnketId)
                .ToListAsync();

            var aCountMemur = await _context.Cevaplars
                .Where(c => anketIDsMemur.Contains((int)c.AnketId) && c.Cevap == "a")
                .CountAsync();

            var bCountMemur = await _context.Cevaplars
                .Where(c => anketIDsMemur.Contains((int)c.AnketId) && c.Cevap == "b")
                .CountAsync();

            var cCountMemur = await _context.Cevaplars
                .Where(c => anketIDsMemur.Contains((int)c.AnketId) && c.Cevap == "c")
                .CountAsync();

            var totalMemur = aCountMemur + bCountMemur + cCountMemur;
            if (totalMemur == 0)
                totalMemur = 1;

            var percentAMemur = ((double)aCountMemur / totalMemur) * 100;
            var percentBMemur = ((double)bCountMemur / totalMemur) * 100;
            var percentCMemur = ((double)cCountMemur / totalMemur) * 100;

            ViewData["percentAMemur"] = percentAMemur;
            ViewData["percentBMemur"] = percentBMemur;
            ViewData["percentCMemur"] = percentCMemur;

            // Müdür verileri
            var anketIDsMudur = await _context.Ankets
                .Where(a => a.TurId == 4)
                .Select(a => a.AnketId)
                .ToListAsync();

            var aCountMudur = await _context.Cevaplars
                .Where(c => anketIDsMudur.Contains((int)c.AnketId) && c.Cevap == "a")
                .CountAsync();

            var bCountMudur = await _context.Cevaplars
                .Where(c => anketIDsMudur.Contains((int)c.AnketId) && c.Cevap == "b")
                .CountAsync();

            var cCountMudur = await _context.Cevaplars
                .Where(c => anketIDsMudur.Contains((int)c.AnketId) && c.Cevap == "c")
                .CountAsync();

            var totalMudur = aCountMudur + bCountMudur + cCountMudur;
            if (totalMudur == 0)
                totalMudur = 1;

            var percentAMudur = ((double)aCountMudur / totalMudur) * 100;
            var percentBMudur = ((double)bCountMudur / totalMudur) * 100;
            var percentCMudur = ((double)cCountMudur / totalMudur) * 100;

            ViewData["percentAMudur"] = percentAMudur;
            ViewData["percentBMudur"] = percentBMudur;
            ViewData["percentCMudur"] = percentCMudur;

            // PartialView'ı döndür
            return PartialView("partial_charts/MesleklerCharts");
        }


        public async Task<IActionResult> SorularCharts()
        { // ilk soru verileri
            var soruBirIDs = await _context.Cevaplars.Where(a => a.SoruId == 1)
                                                     .Select(a => a.Id)
                                                     .ToListAsync();

            var aCountSoruBir = await _context.Cevaplars
                                              .Where(c => soruBirIDs.Contains((int)c.Id) && c.Cevap == "a")
                                              .CountAsync();
            var bCountSoruBir = await _context.Cevaplars
                                              .Where(c => soruBirIDs.Contains((int)c.Id) && c.Cevap == "b")
                                              .CountAsync();
            var cCountSoruBir = await _context.Cevaplars
                                              .Where(c => soruBirIDs.Contains((int)c.Id) && c.Cevap == "c")
                                              .CountAsync();

            var totalSoruBir = aCountSoruBir + bCountSoruBir + cCountSoruBir;
            if (totalSoruBir == 0)
                totalSoruBir = 1;

            ViewData["percentASoruBir"] = ((double)aCountSoruBir / totalSoruBir) * 100;
            ViewData["percentBSoruBir"] = ((double)bCountSoruBir / totalSoruBir) * 100;
            ViewData["percentCSoruBir"] = ((double)cCountSoruBir / totalSoruBir) * 100;

            // ikinci soru verileri
            var soruIkiIDs = await _context.Cevaplars.Where(a => a.SoruId == 2)
                                                     .Select(a => a.Id)
                                                     .ToListAsync();

            var aCountSoruIki = await _context.Cevaplars
                                              .Where(c => soruIkiIDs.Contains((int)c.Id) && c.Cevap == "a")
                                              .CountAsync();
            var bCountSoruIki = await _context.Cevaplars
                                              .Where(c => soruIkiIDs.Contains((int)c.Id) && c.Cevap == "b")
                                              .CountAsync();
            var cCountSoruIki = await _context.Cevaplars
                                              .Where(c => soruIkiIDs.Contains((int)c.Id) && c.Cevap == "c")
                                              .CountAsync();

            var totalSoruIki = aCountSoruIki + bCountSoruIki + cCountSoruIki;
            if (totalSoruIki == 0)
                totalSoruIki = 1;

            var percentASoruIki = ((double)aCountSoruIki / totalSoruIki) * 100;
            var percentBSoruIki = ((double)bCountSoruIki / totalSoruIki) * 100;
            var percentCSoruIki = ((double)cCountSoruIki / totalSoruIki) * 100;

            ViewData["percentASoruIki"] = percentASoruIki;
            ViewData["percentBSoruIki"] = percentBSoruIki;
            ViewData["percentCSoruIki"] = percentCSoruIki;


            //ucuncu soru verileri
            var soruUcIDs = await _context.Cevaplars.Where(a => a.SoruId == 3)
                                                     .Select(a => a.Id)
                                                     .ToListAsync();

            var aCountSoruUc = await _context.Cevaplars
                                              .Where(c => soruUcIDs.Contains((int)c.Id) && c.Cevap == "a")
                                              .CountAsync();
            var bCountSoruUc = await _context.Cevaplars
                                              .Where(c => soruUcIDs.Contains((int)c.Id) && c.Cevap == "b")
                                              .CountAsync();
            var cCountSoruUc = await _context.Cevaplars
                                              .Where(c => soruUcIDs.Contains((int)c.Id) && c.Cevap == "c")
                                              .CountAsync();

            var totalSoruUc = aCountSoruUc + bCountSoruUc + cCountSoruUc;
            if (totalSoruUc == 0)
                totalSoruUc = 1;

            var percentASoruUc = ((double)aCountSoruUc / totalSoruUc) * 100;
            var percentBSoruUc = ((double)bCountSoruUc / totalSoruUc) * 100;
            var percentCSoruUc = ((double)cCountSoruUc / totalSoruUc) * 100;

            ViewData["percentASoruUc"] = percentASoruUc;

AnketProjesi/Views/Charts/ChartsMain.cshtml
@{
    ViewData["Title"] = "ChartsMain";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Anket Sonuçları</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.canvasjs.com/canvasjs.min.js"></script>
    <style>
        #partialViewContainer {
            margin: 1vh;
        }

        /* Container'ı ortalamak için */
        .btn-group-container {
            text-align: center; /* İçeriği ortalar */
        }

        /* Buton grubunun içindeki butonlar */
        .btn-group-container .btn {
            height: 40px; /* Buton yüksekliği */
            width: 250px; /* Buton genişliği */
            margin: 0 5px; /* Butonlar arasındaki boşluk */
        }
    </style>
</head>
<body>
    <div class="container">
        <br>
        <div style="display: flex; justify-content: center;">
            <h1>Anket Sonuçları</h1>
        </div>

        <br>
        <div class="btn-group-container">
            <button id="btnDeneme4" class="btn btn-warning">Bütün Tablolar</button>
            <button id="btnDeneme3" class="btn btn-info">Genel Tablolar</button>
            <button id="btnDeneme1" class="btn btn-primary">Sorulara Göre Filtrele</button>
            <button id="btnDeneme2" class="btn btn-secondary">Mesleklere Göre Filtrele</button>
        </div>

        <div id="partialViewContainer">
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $("#btnDeneme1").click(function () {
                $.ajax({
                    url: '@Url.Action("SorularCharts", "Charts")',
                    type: 'GET',
                    success: function (data) {
                        $("#partialViewContainer").html(data);
                    }
                });
            });

            $("#btnDeneme2").click(function () {
                $.ajax({
                    url: '@Url.Action("MesleklerCharts", "Charts")',
                    type: 'GET',
                    success: function (data) {
                        $("#partialViewContainer").html(data);
                    }
                });
            });

            $("#btnDeneme3").click(function () {
                $.ajax({
                    url: '@Url.Action("GenelTablo", "Charts")',
                    type: 'GET',
                    success: function (data) {
                        $("#partialViewContainer").html(data);
                    }
                });
            });

            $("#btnDeneme4").click(function () {
                $.ajax({
                    url: '@Url.Action("Filtresiz", "Charts")',
                    type: 'GET',
                    success: function (data) {
                        $("#partialViewContainer").html(data);
                    }
                });
            });
        });
    </script>
</body>
</html>